apt_packages:
  - category: text
    pkgs:
      - vim
      - meld
      - texlive-full
      - texstudio
      - okular
  - category: design
    pkgs:
      - gimp
      - f3d
      - openscad
  - category: development
    pkgs:
      - git
      - zsh
      - shellcheck
  - category: admin
    pkgs:
      - keepassxc
      - ansible
      - rsync
  - category: media
    pkgs:
      - vlc
      - ffmpeg
  - category: entertainment
    pkgs:
      - oneko
  - category: finances
    pkgs:
      - gnucash
  - category: storage
    pkgs:
      - nfs-common
      - cachefilesd
  - category: files
    pkgs:
      - wget
      - deluge
      - ncdu
  - category: communication
    pkgs:
      - thunderbird
      - telegram-desktop

software:
  - category: communication
    programs:
      - teamspeak
      - discord
  - category: finance
    programs:
      - portfolio-performance
  - category: media
    programs:
      - yt-dlp
  - category: files
    programs:
      - jdownloader


nas:
  wunderhort:
    - backup
    - dokumente
    - programming
    - stl
    - tabletop
    - passwoerter
    - medien
    - projekte
    - research
    - k8s-nfs-storage-hdd
    - steam
