apt_packages:
  - category: text
    pkgs:
      - vim
      - meld
      - texlive-full
      - texstudio
  - category: design
    pkgs:
      - gimp
      - f3d
      - openscad
  - category: development
    pkgs:
      - git
  - category: admin
    pkgs:
      - keepassxc
      - ansible
      - rsync
  - category: entertainment
    pkgs:
      - vlc
      - oneko
  - category: finances
    pkgs:
      - gnucash
  - category: storage
    pkgs:
      - nfs-common
      - cachefilesd
  - category: files
    pkgs:
      - wget
      - deluge
  - category: communication
    pkgs:
      - thunderbird

software:
  communication:
    - telegram
    - teamspeak
    - discord
  finance:
    - portfolio-performance

nas:
  wunderhort:
    - backup
    - dokumente
    - programming
    - stl
    - tabletop
    - passwoerter
    - medien
    - projekte
    - research
    - k8s-nfs-storage-hdd
    - steam
