deb_packages:
  # text
  - jq
  - yq
  # development
  - git
  - zsh
  - ripgrep
  - shellcheck
  - python-is-python3
  # admin
  - ansible
  - rsync
  - nmap
  - snapd
  - htop
  - powertop
  - lshw
  - oathtool
  - vault
  - ansible
  - terraform
  - tofu
  # media
  # storage
  - nfs-common
  - cachefilesd
  # files
  - wget
  - ncdu
  - 7zip
  - pax
  # communication
  # system
  - ntp
  - dex


nas:
  wunderhort:
    - backup
    - dokumente
    - programming
    - home
    - stl
    - tabletop
    - passwoerter
    - medien
    - projekte
    - research
    - k8s-nfs-storage-hdd
    - steam
    - scratch
  homedirs:
    - Downloads
