---

#- name: Check for existence of installation dir
#  stat:
#    path: /opt/jdtls
#  register: install_dir
#
#- name: Create /opt/jdtls 
#  ansible.builtin.file:
#    path: /opt/jdtls
#    state: directory
#    owner: root
#    group: root
#    mode: '0755'
#  when:
#    - install_dir.stat.exists == false


- name: Import hashicorp gpg key for apt
  block:
    - name: hashicorp repo | get apt key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /etc/apt/trusted.gpg.d/hashicorp.asc
        checksum: sha256:cafb01beac341bf2a9ba89793e6dd2468110291adfbb6c62ed11a0cde6c09029

    - name: adoptium-temurin-openjdk repo | add apt config file
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/hashicorp.asc] https://apt.releases.hashicorp.com  {{ ansible_distribution_release }} main"
        filename: hashicorp.list
        state: present
