- name: Template yt-dlp-archive-script
  ansible.builtin.template:
    src: yt-dlp-archive
    dest: /usr/local/bin/yt-dlp-archive
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Template kustomize resource sorting script
  ansible.builtin.template:
    src: filter-manifests
    dest: /usr/local/bin/detect-undead
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Template kustomize resource generation script
  ansible.builtin.template:
    src: generate-manifests
    dest: /usr/local/bin/animate-dead
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Template kustomize resource removal script
  ansible.builtin.template:
    src: nuke-manifests
    dest: /usr/local/bin/powerword-kill
    owner: root
    group: root
    mode: '0755'
  become: true
