---
- name: Set timezone to Europe/Berlin
  community.general.timezone:
    name: Europe/Berlin
  register: timezone

- name: Restart cron service when the time was changed
  ansible.builtin.service:
    name: cron
    state: restarted
  when: timezone.changed
