---
- name: Set timezone to Europe/Berlin
  ansible.builtin.file:
    dest: /etc/localtime
    src: /usr/share/zoneinfo/Europe/Berlin
    owner: root
    group: root
    state: link
  register: timezone
  become: true

- name: Restart cron service when the time was changed
  ansible.builtin.service:
    name: cron
    state: restarted
  when: timezone.changed and ansible_facts['virtualization_type'] not in ['docker', 'podman', 'container', 'containerd']
  become: true
  
