
---
- name: Desktop PC setup playbook
  hosts: localhost
  remote_user: leon
  gather_facts: true

  roles:
    ## BEGIN ALWAYS REQUIRED ##
    - ../roles/variable_definitions
    ## END ALWAYS REQUIRED ##
    - ../roles/config
    - ../roles/time
    - ../roles/cleanup
