---
- name: Build list of all packages
  set_fact:
    all_packages: "{{ all_packages | default([]) | union(item.pkgs) }}"
  with_items: "{{ apt_packages }}"

- name: Print out list of apt packages
  debug:
    msg: "{{ all_packages }}"

- name: Install software using apt
  when: ansible_os_family == 'Debian'
  apt:
    pkg: "{{ all_packages }}"

- name: Create lightdm.conf
  ansible.builtin.template:
    src: lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf
    owner: root
    group: root
    mode: '0644'

- name: Create display-setup.sh
  ansible.builtin.template:
    src: display-setup.sh.j2
    dest: /usr/local/bin/display-setup.sh
    owner: root
    group: root
    mode: '0755'

