---
base_generic_packages:
  # passwords
  keepassxc:

base_special_packages:
  Debian: {}
  Ubuntu: {}
  Archlinux: {}

# TODO: explain why we blacklisted these. I think these have something to do with multilanguage input
# which got really annoyong
base_generic_blacklist:
  uim:
  ibus:

base_special_blacklist:
  Debian: {}
  Ubuntu: {}
  Archlinux: {}
