---
development_generic_packages:
  # c/c++
  cmake:
  astyle: # source code formatter c/c++ java https://astyle.sourceforge.net/
  # linux
  build-essential:
  shellcheck:
  linux-headers-amd64:
    Ubuntu: linux-headers-generic
    Archlinux: linux-headers
  # git
  git:
  fzf: # requirement for delta (thingy that displays nicer git diffs)
  git-crypt:
  # python
  pipx:
    Archlinux: python-pipx
  # java
  maven:
  java-common:
    Archlinux: jdk-openjdk
  # diagrams
  graphviz: # https://graphviz.org/
  plantuml: # https://plantuml.com/
  # web
  hugo:
  # js
  nodejs:
  nodejs-corepack:
    Archlinux: corepack
    Debian: node-corepack
  # ides
  codium:
    Archlinux: code
  meld:
  neovim:
  xsel:    # we use this to make the nvim clipboard and the Xserver clipboard sync
  # iac
  ansible:
  ansible-lint:
  yamllint:
  terraform:
  # containers
  podman:
  docker.io:
    Archlinux: docker
  docker-compose:
  # vms
  packer:
  qemu-utils:
    Debian: qemu-utils
    Archlinux: qemu-tools
  # secrets
  oathtool:
    Archlinux: oath-toolkit
  age:
  vault:
  # 3d printing / modelling
  f3d:
  openscad:

# TODO: boil down this list, we should find the relevant packages on Arch
# alternatively, get rid of stuff / replace
development_special_packages:
  Debian:
    temurin-26-jdk:
    python-is-python3:
    vagrant:
    alien:
    genisoimage:
    firmware-misc-nonfree:
  Ubuntu:
    temurin-26-jdk:
    python-is-python3:
    vagrant:
    genisoimage:
    linux-firmware:
  Archlinux: {}
