---
entertainment_generic_packages:
  wine:
  winetricks:
  # peripherals / system
  solaar:

entertainment_special_packages:
  Debian:
    oneko:
    qbrew:
  Ubuntu:
    oneko:
    qbrew:
  Archlinux: {}
