# https://github.com/ollama/ollama/blob/main/docs/linux.md

- name: Download archive for ollama
  ansible.builtin.get_url:
    url: https://ollama.com/download/ollama-linux-amd64.tgz
    dest: /var/ansible-cache/ollama.tar.gz
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Recursively delete /usr/lib/ollama directory
  ansible.builtin.file:
    path: /usr/lib/ollama
    state: absent
  become: true

- name: Unpack archive
  ansible.builtin.unarchive:
    src: /var/ansible-cache/ollama.tar.gz
    dest: /usr
    remote_src: true
  become: true

- name: Create a system group ollama
  ansible.builtin.group:
    name: "ollama"
    system: true
  become: true

- name: Create the system user ollama
  ansible.builtin.user:
    name: ollama
    group: ollama
    create_home: true
    system: true
  become: true


# - name: "Add ollama to linuxbrew group"
#   ansible.builtin.user:
#     name: "{{ linuxbrew_user }}"
#     append: true
#     groups: linuxbrew
#   become: true

- name: Template /etc/systemd/system/ollama.service
  ansible.builtin.template:
    src: ollama.service.j2
    dest: /etc/systemd/system/ollama.service
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Enable ollama service
  ansible.builtin.service:
    name: ollama.service
    state: reloaded
    enabled: true
  become: true
