- name: Check existence of user config repo dir
  ansible.builtin.stat:
    path: "{{ target_home }}/.cfg.git"
  register: config_repo_dir
- debug:
    var: config_repo_dir
  

- name: Perform user config repo checkout
  ansible.builtin.include_tasks: config_repo_checkout.yaml
  when: config_repo_dir.stat.exists == false

- name: Ensure config repo is configured to use SSH for upstream access
  ansible.builtin.lineinfile:
    path: "{{ target_home }}/.cfg.git/config"
    # \s* matches any number of whitespace
    regexp: '\s*url\s*=\ https:\/\/github\.com\/Atomsoldat\/cfg-files\.git'
    line: '    url = git@github.com:Atomsoldat/cfg-files.git'