# this gets evaluated when the playbook is executed, before any
# become-statements; this way, we can retain the actual user info
# even in tasks with become: true
target_user: "{{ lookup('env', 'USER') }}"
target_home: "{{ lookup('env', 'HOME') }}"