---
- name: Docker repo | Get apt key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570
    mode: '0644'
  become: true

- name: Docker repo | Add apt config file
  ansible.builtin.template:
    src: docker.sources.j2
    dest: /etc/apt/sources.list.d/docker.sources
    owner: root
    group: root
    mode: "0644"
  become: true
