---
- name: Import hashicorp gpg key for apt
  block:
    - name: hashicorp repo | Get apt key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /etc/apt/trusted.gpg.d/hashicorp.asc
        checksum: sha256:cafb01beac341bf2a9ba89793e6dd2468110291adfbb6c62ed11a0cde6c09029
        mode: '0644'

- name: Hashicorp repo | Add apt config file
  ansible.builtin.template:
    src: hashicorp.sources.j2
    dest: /etc/apt/sources.list.d/hashicorp.sources
    owner: root
    group: root
    mode: "0644"
