---
- name: VSCodium repo | Get apt key
  ansible.builtin.get_url:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    dest: /etc/apt/trusted.gpg.d/vscodium.asc
    checksum: sha256:dbdfd9af3b83b72a24c89160ce7638418142e2cf4736ab53e5061e10070f13c1
    mode: '0644'
  become: true

- name: VSCodium repo | Add apt config file
  ansible.builtin.template:
    src: vscodium.sources.j2
    dest: /etc/apt/sources.list.d/vscodium.sources
    owner: root
    group: root
    mode: "0644"
  become: true
