---
- name: "Add the user {{ target_user }} with a zsh shell, appending groups needed for our config"
  ansible.builtin.user:
    name: "{{ target_user }}"
    shell: /bin/zsh
    groups: sudo,docker,linuxbrew
    append: true
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: "Add the user {{ target_user }} with a zsh shell, appending groups needed for our config"  
  ansible.builtin.user:
    name: "{{ target_user }}"
    shell: /bin/zsh
    groups: wheel,docker,linuxbrew
    append: true
  become: true
  when: ansible_facts['os_family'] == 'Archlinux'
