- name: Add the flathub flatpak repository remote to the system installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpack packages
  community.general.flatpak:
    name: "{{ item.identifier }}"
  with_items: "{{ flatpaks }}"

- name: Create start scripts in /usr/local/bin for flatpaks
  ansible.builtin.template:
    src: startscript.j2
    dest: "/usr/local/bin/{{ item.alias }}"
    owner: root
    group: root
    mode: '0755'
  with_items: "{{ flatpaks }}"

