---
- name: Check for existance of binary
  stat:
    path: /usr/local/bin/kustomize
  register: installed_binary

- name: Download archive wijth check (md5)
  ansible.builtin.get_url:
    url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.3/kustomize_v5.4.3_linux_amd64.tar.gz
    dest: /var/ansible-cache/kustomize.tar.gz
    checksum: sha256:3669470b454d865c8184d6bce78df05e977c9aea31c30df3c669317d43bcc7a7
  when:
    - installed_binary.stat.exists == false

- name: Unarchive file on the remote machine
  ansible.builtin.unarchive:
    src: /var/ansible-cache/kustomize.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  when:
    - installed_binary.stat.exists == false

- name: Set up permissions for kustomize binary
  ansible.builtin.file:
    dest: /usr/local/bin/kustomize
    owner: root
    group: root
    mode: '0755' 
  when:
    - installed_binary.stat.exists == false
