---

- name: Ensure /var/ansible-cache exists
  file:
    path: /var/ansible-cache
    state: directory
    owner: root
    group: root
    mode: 0755

- include_tasks: sweet_home_3d.yaml
- include_tasks: portfolio_performance.yaml
- include_tasks: vscodium.yaml
- include_tasks: kubectl.yaml
- include_tasks: helm.yaml
- include_tasks: neovim.yaml
- include_tasks: spacevim.yaml
- include_tasks: sops.yaml
- include_tasks: kustomize.yaml
- include_tasks: kubeconform.yaml
- include_tasks: kubent.yaml
- include_tasks: helmfile.yaml
- include_tasks: clusterctl.yaml
- include_tasks: istioctl.yaml
- include_tasks: yq_mf.yaml
# we try to let our IDE manage this for now 20240820
#- include_tasks: jdtls.yaml
#
- include_tasks: flatpaks.yaml
# needs more work
#- include_tasks: snaps.yaml

