---
- name: Check for existance of binary
  stat:
    path: /usr/local/bin/nvim
  register: installed_binary

- name: Download archive
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-x86_64.appimage
    dest: /var/ansible-cache/nvim-linux-x86_64.appimage
    checksum: sha256:d1b1488ef6a970dc3a2826b788d31d81b2f308ad42ef70ed62d35d0bf6189336
  when:
    - installed_binary.stat.exists == false
  become: true

- name: Copy binary to destination
  ansible.builtin.copy:
    src: /var/ansible-cache/nvim-linux-x86_64.appimage
    dest: /usr/local/bin/nvim
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  when:
    - installed_binary.stat.exists == false
  become: true

- name: Set up permissions for neovim
  ansible.builtin.file:
    dest: /usr/local/bin/nvim
    owner: root
    group: root
    mode: '0755'
  when:
    - installed_binary.stat.exists == false
  become: true

- name: Make sure vim package is not installed
  ansible.builtin.apt:
    package: vim
    state: absent
  become: true

- name: Create vim -> nvim symlink
  ansible.builtin.file:
    src: /usr/local/bin/nvim
    dest: /usr/local/bin/vim
    owner: root
    group: root
    state: link
  become: true

