---
- name: Check for existance of installation dir
  stat:
    path: /opt/portfolio
  register: install_dir

- name: Download archive with check (md5)
  ansible.builtin.get_url:
    url: https://github.com/buchen/portfolio/releases/download/0.70.4/PortfolioPerformance-0.70.4-linux.gtk.x86_64.tar.gz
    dest: /var/ansible-cache/PortfolioPerformance.tar.gz
    checksum: md5:f5939b2299db8c0bd0d402c116dccc7f
  when:
    - install_dir.stat.exists == false


- name: Unarchive file on the remote machine
  ansible.builtin.unarchive:
    # md5sum matches either way
    src: /var/ansible-cache/PortfolioPerformance.tar.gz
    dest: /opt
    remote_src: yes
  when:
    - install_dir.stat.exists == false

- name: Create .desktop shortcut
  ansible.builtin.copy:
    src: portfolio_performance.desktop
    dest: /usr/share/applications/portfolio.desktop
    owner: root
    group: root
    mode: '0644'
  when: 
    - install_dir.stat.exists == false
