---
# doesn't work for libraries
#- name: Install pynvim package from pipx
#  community.general.pipx:
#    name: pynvim

- name: Install python3-pynvim apt package
  ansible.builtin.apt:
    package: python3-pynvim
    state: present

# the script file will need to be updated when new versions are released
# the devs expect you to pipe curl into bash like some maniac
# see here: https://spacevim.org/quick-start-guide/
# and here https://spacevim.org/install.sh
- name: Run Spacevim installation script
  ansible.builtin.script:
    cmd: spacevim-install.sh --install
  become_user: leon

