---
- name: Include desktop variables if host is localhost and host_type is set to 'desktop'
  include_vars: "{{ ansible_env.PWD }}/group_vars/workstation.yaml"
  when: host_type == 'desktop' or
    host_type == 'laptop'
