---
# Override software_bundles via CLI to select which package domains to install:
#   -e '{"software_bundles": ["base", "development", "communication"]}'
- name: Desktop PC setup playbook
  hosts: localhost
  gather_facts: true

  vars:
    software_bundles:
      - base
      - cli_tools
      - desktop_environment
      - development
      #- entertainment
      #- latex
      - office_software
      #- private_networking
      - sysadmin

  roles:
    - ../roles/packaged_software
    - ../roles/nix_setup
    - ../roles/third_party_software
    - ../roles/scripts
