
---
- name: Desktop PC setup playbook
  hosts: localhost
  remote_user: leon
  gather_facts: true

  roles:
    - ../roles/packaged_software
    - ../roles/third_party_software
    - ../roles/scripts
