#!/bin/bash

# This script will hydrate the kustomisation of in each components subdirectory
# or a specified subdirectory in components

set -exo pipefail

if [[ ! -z "$1" ]]; then
	components=("$1")
else
	components=("$(ls ./components)")
fi

set -u
for subdir in "${components[@]}"; do

	output_path="./manifests/${subdir}"
	mkdir -p "${output_path}"

	kustomize build components/"${subdir}" --enable-helm > "${output_path}"/resources.yaml

done
