#!/bin/bash

# This script will hydrate the kustomisation of in each components subdirectory

set -euxo pipefail

builddir=$(mktemp -d)

function cleanup(){
	rm -rf ${builddir}
}

# run cleanup function no matter what
trap cleanup EXIT

for subdir in $(ls ./components); do

	output_path="./manifests/${subdir}"
	mkdir -p ${output_path}

	kustomize build components/${subdir} --enable-helm > ${output_path}/resources.yaml

done

