- name: Check if homedir files/directories exist
  stat:
    path: "/home/leon/{{ item }}"
  register: "homedir_stats"
  loop: "{{ nas.homedirs }}"

- ansible.builtin.debug:
    var: "homedir_stats.results" 

- ansible.builtin.fail:
    msg: "Failing, because {{ item.stat.path }} is a directory"
  when: 
    - item.stat.isdir is defined
    - item.stat.isdir == true
  loop: "{{ homedir_stats.results }}"

- name: Link homedir directories to wunderhort    
  ansible.builtin.file:    
    src: "/wunderhort/home/{{ item }}"    
    dest: "/home/leon/{{ item }}"   
    owner: leon    
    group: leon    
    state: link    
  loop: "{{ nas.homedirs }}"
