---
- name: copy font files into /usr/local/share/fonts
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: "/usr/local/share/fonts/"
  with_items:
    - eb-garamond
    - unifraktur-maguntia
    - unifraktur-cook
    - refraktury

- name: Recursively set permissions on /usr/local/share/fonts
  ansible.builtin.file:
    dest: /usr/local/share/fonts
    owner: root
    group: staff
    mode: "u=rwX,g=rwX,o=rX"
    recurse: true
